# Generated by Django 2.1.7 on 2019-04-03 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='directory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='extension',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
