---
  - name: associate new elastic IPs with each of the instances
    ec2_eip:
      ip: "{{ elastic_ip }}"
      region: "{{ aws_region }}"
      instance_id: "{{ item.id }}"
    with_items: "{{ ec2.instances }}"

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    loop: "{{ ec2.instances }}"


