---
  - name: install docker.io with apt
    apt: name={{ item }} update_cache=yes
    update_cache: yes
    with_items:
      - docker.io


  - name: pip in the docker py libraries
    pip:
      name: pip
      extra_args: --upgrade



  - name: pip in the docker py libraries
    pip:
      name: docker   # docker-py is the older one
      extra_args: --upgrade


# todo add local user to docker usergroup
#sudo usermod -aG docker $USER