---
# - hosts: tag_AnsibleType_AnsibleWebserver
 - hosts: tag_AnsibleType_{{type}}
   vars:
    #ansible_python_interpreter: "/usr/bin/env python"
    ansible_python_interpreter: "/usr/bin/python3"
   gather_facts: true
   become: yes
   become_user: root
   become_method: sudo
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   roles:
    - add-python2


    #sudo apt-get install python-minimal -y



