---
 - name: Host Type
   debug: type={{type}} : Running on ec2 hosts with AnsibleType of '{{type}}'

 - hosts: tag_AnsibleType_{{type}}
   gather_facts: true
   become: yes
   become_user: root
   become_method: sudo
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   roles:
    - add-docker
    - add-service-scenespace

#   handlers:
#    - include: handlers/main.yml
