---
 - hosts: all
   gather_facts: false
   become: yes
   become_user: root
   become_method: sudo
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   roles:
    - add-docker
    - add-flask

