---
 - hosts: tag_AnsibleType_{{type}}
   gather_facts: true
   become: yes
   become_user: root
   become_method: sudo
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   roles:
    - add-docker
    - add-service-media  # made into its own playbook
    - add-service-grabcut  # made into its own playbook
    - add-flask
    - add-fileupload
    - add-haproxy

   handlers:
    - include: handlers/main.yml
