---
 - hosts: localhost
   connection: local
   gather_facts: false
#testing this
#   user: root
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   tasks:

    - name: Gather facts about current Production
      ec2_instance_facts:
        region: "{{aws_region}}"
        filters:
          "tag:Name": Production
      register: old_prod

    - name: Gather facts about Staging
      ec2_instance_facts:
        region: "{{aws_region}}"
        filters:
          "tag:Name": Staging
      register: new_prod

#    - debug: msg="{{ rollthisback.instances }}"
#    - debug: msg="{{ rollthisback.instances[0].public_ip_address }}"
#    - debug: msg="{{ previousproduction.instances }}"
#    - debug: msg="{{ previousproduction.instances[0].public_ip_address }}"


    - name: tag Production -> Rollback
      ec2_tag:
        state: present
        resource: "{{ item.instance_id }}"
        region: "{{ aws_region }}"

        tags:
          Name: Rollback
      with_items: "{{ old_prod.instances }}"


    - name: tag Staging -> Production
      ec2_tag:
        state: present
        resource: "{{ item.instance_id }}"
        region: "{{ aws_region }}"
        tags:
          Name: Production
      with_items: "{{ new_prod.instances }}"

    - name: associate new elastic IPs with each of the instances
      ec2_eip:
        ip: "{{ elastic_ip }}"
        region: "{{ aws_region }}"
        instance_id: "{{ item.instance_id }}"
      with_items: "{{ new_prod.instances }}"





