---
  - name: Synchronization of fileupload to the remote hosts
    synchronize:
      src: ../example/node-file-upload
      dest: "{{ working_dir }}"
    register: sync_result


  - name: Build fileupload image and with buildargs
    docker_image:
      name: node-file-upload
      path: "{{ working_dir }}/node-file-upload"
      tag: ex1
      state: present
      buildargs:
        log_volume: /var/log/node-file-upload
        listen_port: 3200
    #when: sync_result.changed

  - name: ensure a fileupload container is running
    docker_container:
      name: ex1-fileupload
#      state: started
      state: started
      image: "node-file-upload:ex1"
      #pull: true
      ports:
        - "3200:3200"
      volumes:
        - "{{ efs_mount_dir }}/m:/usr/src/app/fu"
#      env:
#        EXT_URL_BASE: "http://{{ ansible_host }}"


#
#  - name: checkout health monitoring tools
#    git:
#      repo: "https://github.com/Runscope/healthcheck"
#      dest: "{{ working_dir }}/healthcheck"
##      version: release-0.22