# Generated by Django 2.1.7 on 2019-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundtruth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='frameNo',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='image',
            name='sceneNo',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='image',
            name='shotNo',
            field=models.IntegerField(default=-1),
        ),
    ]
