# Generated by Django 2.1.7 on 2019-07-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundtruth', '0002_auto_20190727_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='frameNo',
            new_name='frame_no',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='sceneNo',
            new_name='scene_no',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='shotNo',
            new_name='shot_no',
        ),
    ]
