---
  - name: install HAProxy w apt
    apt: name={{ item }} update_cache=yes state=present
    update_cache: yes
    with_items:
      - haproxy

  - name: Enable init script on HAProxy
    replace: dest='/etc/default/haproxy'
           regexp='ENABLED=0'
           replace='ENABLED=1'

  - name: Update HAProxy config
    template: src=templates/haproxy.cfg
          dest=/etc/haproxy/haproxy.cfg
          backup=yes
    notify:
      - restart haproxy

#handler is defined in ansible /handlers dir
#   handlers:
#    - include: handlers/main.yml