---
  - name: Provision a set of instances
    ec2:
      keypair: "{{keypair}}"
      region: "{{aws_region}}"
      group: "{{security_group}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      #count: 2
      instance_tags:
         AnsibleName: AnsibleFlask
         AnsibleType: "{{ ansible_type }}"
      exact_count: "{{ count }}"
      count_tag:
         AnsibleName: AnsibleFlask

    register: ec2

#  - name: Wait for SSH to be available
#    pause: minutes=2

  - name: Wait for SSH to come up
    local_action: wait_for
                  host={{ item.public_ip }}
                  port=22
                  state=started
    with_items: "{{ ec2.instances }}"

  - name: Show the public ip and dns name for each EC2 instance
    debug: msg="Instance {{ item.id }} IP {{ item.public_ip }} NAME {{ item.public_dns_name }}"
    with_items: "{{ ec2.instances }}"

#  - name: associate new elastic IPs with each of the instances
#    ec2_eip:
#      ip: "{{ elastic_ip }}"
#      region: "{{ aws_region }}"
#      instance_id: "{{ item.id }}"
#    with_items: "{{ ec2.instances }}"
#
#  - name: Add all instance public IPs to host group
#    add_host: hostname={{ item.public_ip }} groups=ec2hosts
#    loop: "{{ ec2.instances }}"
#

